CREATE TABLE RANG(
   ID_RANG INT,
   RANG VARCHAR(50),
   PRIMARY KEY(ID_RANG)
);

CREATE TABLE DIGNITE(
   ID_DIGNITE INT,
   DIGNITE VARCHAR(50),
   PRIMARY KEY(ID_DIGNITE)
);

CREATE TABLE ADRESSE_PARTENAIRE(
   ID_PARTENAIRE INT,
   NOM VARCHAR(50),
   ADRESSE VARCHAR(70) NOT NULL,
   PRIMARY KEY(ID_PARTENAIRE)
);

CREATE TABLE TITRE(
   ID_TITRE INT,
   TITRE VARCHAR(50),
   PRIMARY KEY(ID_TITRE)
);

CREATE TABLE ENTREPRISE(
   ID_ENTREPRISE INT,
   RAISONSOCIALE VARCHAR(50),
   SIRET CHAR(14),
   PRIMARY KEY(ID_ENTREPRISE)
);

CREATE TABLE GRADE(
   ID_GRADE INT,
   GRADE VARCHAR(50),
   PRIMARY KEY(ID_GRADE)
);

CREATE TABLE ORGANISME(
   ID_ORGANISME INT,
   PRIMARY KEY(ID_ORGANISME)
);

CREATE TABLE PLAT(
   ID_PLAT INT,
   INTITULE VARCHAR(50),
   PRIMARY KEY(ID_PLAT)
);

CREATE TABLE SAUCE(
   ID_SAUCE INT,
   NOM VARCHAR(50),
   PRIMARY KEY(ID_SAUCE)
);

CREATE TABLE ALLERGIES(
   ID_ALLERGENE INT,
   NOM VARCHAR(50),
   PRIMARY KEY(ID_ALLERGENE)
);

CREATE TABLE CROYANCE(
   ID_CROYANCE INT,
   NOM VARCHAR(50),
   PRIMARY KEY(ID_CROYANCE)
);

CREATE TABLE INGREDIENT(
   ID_INGREDIENT INT,
   NOM VARCHAR(50),
   PRIMARY KEY(ID_INGREDIENT)
);

CREATE TABLE GENRE(
   ID_GENRE INT,
   GENRE VARCHAR(50),
   PRIMARY KEY(ID_GENRE)
);

CREATE TABLE ROLE(
   ID_ROLE INT,
   ROLE VARCHAR(50),
   PRIMARY KEY(ID_ROLE)
);

CREATE TABLE CONVICTIONS(
   ID_CONVICTION INT,
   CONVICTION VARCHAR(50),
   PRIMARY KEY(ID_CONVICTION)
);

CREATE TABLE ORDRE(
   ID_ORGANISME INT,
   DATE_DE_CREATION DATE,
   PRIMARY KEY(ID_ORGANISME),
   FOREIGN KEY(ID_ORGANISME) REFERENCES ORGANISME(ID_ORGANISME)
);

CREATE TABLE CLUB(
   ID_ORGANISME_1 INT,
   NOM VARCHAR(50),
   ID_ORGANISME INT,
   PRIMARY KEY(ID_ORGANISME_1),
   FOREIGN KEY(ID_ORGANISME_1) REFERENCES ORGANISME(ID_ORGANISME),
   FOREIGN KEY(ID_ORGANISME) REFERENCES ORDRE(ID_ORGANISME)
);

CREATE TABLE LEGUME(
   ID_INGREDIENT INT,
   PRIMARY KEY(ID_INGREDIENT),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT)
);

CREATE TABLE REGISTRE(
   ID_ORGANISME INT,
   ID_REGISTRE INT,
   DATE_OUVERTURE DATE,
   DERNIERE_MODIFICATION DATE,
   PRIMARY KEY(ID_ORGANISME, ID_REGISTRE),
   FOREIGN KEY(ID_ORGANISME) REFERENCES ORGANISME(ID_ORGANISME)
);

CREATE TABLE TENRAC(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   NOM VARCHAR(50),
   PRENOM VARCHAR(50),
   COURRIEL VARCHAR(50),
   ADRESSE VARCHAR(50),
   TELEPHONE_PORTABLE VARCHAR(20),
   TELEPHONE_FIXE VARCHAR(20),
   ID_GENRE INT NOT NULL,
   ID_TITRE INT,
   ID_RANG INT,
   ID_DIGNITE INT,
   ID_GRADE INT NOT NULL,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_ORGANISME) REFERENCES ORGANISME(ID_ORGANISME),
   FOREIGN KEY(ID_GENRE) REFERENCES GENRE(ID_GENRE),
   FOREIGN KEY(ID_TITRE) REFERENCES TITRE(ID_TITRE),
   FOREIGN KEY(ID_RANG) REFERENCES RANG(ID_RANG),
   FOREIGN KEY(ID_DIGNITE) REFERENCES DIGNITE(ID_DIGNITE),
   FOREIGN KEY(ID_GRADE) REFERENCES GRADE(ID_GRADE)
);

CREATE TABLE CARTE(
   ID_CARTE INT,
   DATE_DE_DELIVRANCE DATE,
   DATE_FIN_VALIDITE DATE,
   ID_ENTREPRISE INT NOT NULL,
   ID_ORGANISME INT NOT NULL,
   ID_MEMBRE INT NOT NULL,
   PRIMARY KEY(ID_CARTE),
   FOREIGN KEY(ID_ENTREPRISE) REFERENCES ENTREPRISE(ID_ENTREPRISE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE)
);

CREATE TABLE TENRAC_IMPORTANT(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   POSITION_ VARCHAR(50),
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE)
);

CREATE TABLE RDV(
   ID_RDV INT,
   HEURE TIME NOT NULL,
   DATE_ DATE NOT NULL,
   ID_PARTENAIRE INT NOT NULL,
   ID_ORGANISME INT NOT NULL,
   ID_MEMBRE INT NOT NULL,
   PRIMARY KEY(ID_RDV),
   FOREIGN KEY(ID_PARTENAIRE) REFERENCES ADRESSE_PARTENAIRE(ID_PARTENAIRE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC_IMPORTANT(ID_ORGANISME, ID_MEMBRE)
);

CREATE TABLE CERTIFICATION_ENTRETIEN(
   ID_CERTIFICATION VARCHAR(50),
   DATE_DE_CERTIFICATION DATE,
   ID_ORGANISME INT NOT NULL,
   ID_MEMBRE INT NOT NULL,
   PRIMARY KEY(ID_CERTIFICATION),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC_IMPORTANT(ID_ORGANISME, ID_MEMBRE)
);

CREATE TABLE TYPE_ENTRETIEN(
   ID_CERTIFICATION VARCHAR(50),
   ID_TYPE INT,
   TYPE VARCHAR(50),
   NOM VARCHAR(50),
   PERIODICITE VARCHAR(50),
   PRIMARY KEY(ID_CERTIFICATION, ID_TYPE),
   FOREIGN KEY(ID_CERTIFICATION) REFERENCES CERTIFICATION_ENTRETIEN(ID_CERTIFICATION)
);

CREATE TABLE MACHINE(
   ID_MACHINE INT,
   NOM VARCHAR(50),
   ID_CERTIFICATION VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_MACHINE),
   UNIQUE(ID_CERTIFICATION),
   FOREIGN KEY(ID_CERTIFICATION) REFERENCES CERTIFICATION_ENTRETIEN(ID_CERTIFICATION)
);

CREATE TABLE MODELE(
   ID_MACHINE INT,
   ID_MODELE INT,
   NOM VARCHAR(50),
   MARQUE VARCHAR(50),
   ID_CERTIFICATION VARCHAR(50) NOT NULL,
   ID_TYPE INT NOT NULL,
   PRIMARY KEY(ID_MACHINE, ID_MODELE),
   FOREIGN KEY(ID_MACHINE) REFERENCES MACHINE(ID_MACHINE),
   FOREIGN KEY(ID_CERTIFICATION, ID_TYPE) REFERENCES TYPE_ENTRETIEN(ID_CERTIFICATION, ID_TYPE)
);

CREATE TABLE COOPERE(
   ID_ORGANISME INT,
   ID_PARTENAIRE INT,
   PRIMARY KEY(ID_ORGANISME, ID_PARTENAIRE),
   FOREIGN KEY(ID_ORGANISME) REFERENCES ORDRE(ID_ORGANISME),
   FOREIGN KEY(ID_PARTENAIRE) REFERENCES ADRESSE_PARTENAIRE(ID_PARTENAIRE)
);

CREATE TABLE REUNION(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   ID_RDV INT,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE, ID_RDV),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_RDV) REFERENCES RDV(ID_RDV)
);

CREATE TABLE COMPOSE(
   ID_PLAT INT,
   ID_INGREDIENT INT,
   PRIMARY KEY(ID_PLAT, ID_INGREDIENT),
   FOREIGN KEY(ID_PLAT) REFERENCES PLAT(ID_PLAT),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT)
);

CREATE TABLE DEGUSTE(
   ID_RDV INT,
   ID_PLAT INT,
   PRIMARY KEY(ID_RDV, ID_PLAT),
   FOREIGN KEY(ID_RDV) REFERENCES RDV(ID_RDV),
   FOREIGN KEY(ID_PLAT) REFERENCES PLAT(ID_PLAT)
);

CREATE TABLE CONSTITUE(
   ID_SAUCE INT,
   ID_INGREDIENT INT,
   PRIMARY KEY(ID_SAUCE, ID_INGREDIENT),
   FOREIGN KEY(ID_SAUCE) REFERENCES SAUCE(ID_SAUCE),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT)
);

CREATE TABLE UTILISE(
   ID_RDV INT,
   ID_MACHINE INT,
   PRIMARY KEY(ID_RDV, ID_MACHINE),
   FOREIGN KEY(ID_RDV) REFERENCES RDV(ID_RDV),
   FOREIGN KEY(ID_MACHINE) REFERENCES MACHINE(ID_MACHINE)
);

CREATE TABLE DONNE(
   ID_INGREDIENT INT,
   ID_ALLERGENE INT,
   PRIMARY KEY(ID_INGREDIENT, ID_ALLERGENE),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT),
   FOREIGN KEY(ID_ALLERGENE) REFERENCES ALLERGIES(ID_ALLERGENE)
);

CREATE TABLE ACCOMPAGNE(
   ID_PLAT INT,
   ID_SAUCE INT,
   PRIMARY KEY(ID_PLAT, ID_SAUCE),
   FOREIGN KEY(ID_PLAT) REFERENCES PLAT(ID_PLAT),
   FOREIGN KEY(ID_SAUCE) REFERENCES SAUCE(ID_SAUCE)
);

CREATE TABLE ALLERGIQUE_A_(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   ID_ALLERGENE INT,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE, ID_ALLERGENE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_ALLERGENE) REFERENCES ALLERGIES(ID_ALLERGENE)
);

CREATE TABLE HEURT(
   ID_INGREDIENT INT,
   ID_CROYANCE INT,
   PRIMARY KEY(ID_INGREDIENT, ID_CROYANCE),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT),
   FOREIGN KEY(ID_CROYANCE) REFERENCES CROYANCE(ID_CROYANCE)
);

CREATE TABLE CROIT(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   ID_CROYANCE INT,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE, ID_CROYANCE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_CROYANCE) REFERENCES CROYANCE(ID_CROYANCE)
);

CREATE TABLE ARCHIVE(
   ID_ORGANISME INT,
   ID_REGISTRE INT,
   ID_CERTIFICATION VARCHAR(50),
   ID_TYPE INT,
   PRIMARY KEY(ID_ORGANISME, ID_REGISTRE, ID_CERTIFICATION, ID_TYPE),
   FOREIGN KEY(ID_ORGANISME, ID_REGISTRE) REFERENCES REGISTRE(ID_ORGANISME, ID_REGISTRE),
   FOREIGN KEY(ID_CERTIFICATION, ID_TYPE) REFERENCES TYPE_ENTRETIEN(ID_CERTIFICATION, ID_TYPE)
);

CREATE TABLE A_UN(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   ID_ROLE INT,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE, ID_ROLE),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC_IMPORTANT(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_ROLE) REFERENCES ROLE(ID_ROLE)
);

CREATE TABLE A_DES(
   ID_ORGANISME INT,
   ID_MEMBRE INT,
   ID_CONVICTION INT,
   PRIMARY KEY(ID_ORGANISME, ID_MEMBRE, ID_CONVICTION),
   FOREIGN KEY(ID_ORGANISME, ID_MEMBRE) REFERENCES TENRAC(ID_ORGANISME, ID_MEMBRE),
   FOREIGN KEY(ID_CONVICTION) REFERENCES CONVICTIONS(ID_CONVICTION)
);

CREATE TABLE TRANSGRESSE(
   ID_INGREDIENT INT,
   ID_CONVICTION INT,
   PRIMARY KEY(ID_INGREDIENT, ID_CONVICTION),
   FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT),
   FOREIGN KEY(ID_CONVICTION) REFERENCES CONVICTIONS(ID_CONVICTION)
);

ALTER TABLE ENTREPRISE ADD COLUMN ADRESSE_POSTALE VARCHAR(255);
ALTER TABLE ENTREPRISE ADD COLUMN COURRIEL VARCHAR(100);
ALTER TABLE ENTREPRISE ADD COLUMN TELEPHONE VARCHAR(20);

ALTER TABLE CARTE ADD COLUMN CODE_RFID VARCHAR(255) UNIQUE NOT NULL;